---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-app
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-app
data:
  mysql-password: ${MYSQL_PASSWORD}
  mysql-root-password: ${MYSQL_ROOT_PASSWORD}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: flask-app
data:
  mysql-db-name: student
  mysql-db-user: devops
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: flask-app
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.0.29
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: "MYSQL_USER"
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-db-user
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: "MYSQL_DATABASE"
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-db-name
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
            subPath: mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: flask-app
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql
      name: mysql
